<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StaticWebAssetBasePath>App_Plugins/Pixelbuilders.Umbraco.ElementFinder</StaticWebAssetBasePath>
    <Product>Pixelbuilders.Umbraco.ElementFinder</Product>
    <Title>Pixelbuilders.Umbraco.ElementFinder</Title>
    <Description>An Umbraco extension that adds a tab to the documents in the Setting tab in the CMS to allow users to search for elements and page types being used within the CMS.</Description>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Version>17.0.0-beta.2</Version>
    <Authors>Pixelbuilders</Authors>
    <Copyright>2026 © Pixelbuilders</Copyright>
    <RepositoryUrl>https://github.com/pixelbuilders/PixelBuilders.Umbraco.ElementFinder</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="17.4.0" />
  </ItemGroup>

</Project>
